# Generated by Django 3.2.5 on 2021-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('cost', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('ELEC_GAS', 'Electricity/Gas'), ('MOBILE', 'Mobile'), ('INTERNET', 'Internet'), ('WATER', 'Water'), ('GROCERIES', 'Groceries'), ('INSUR_HEALTH', 'Health Insurance')], max_length=30)),
            ],
        ),
    ]
