# Generated by Django 3.2.5 on 2021-07-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210710_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assignee', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('groupTransactions', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('dateStart', models.DateTimeField(verbose_name='dateStart')),
                ('dateEnd', models.DateTimeField(verbose_name='dateEnd')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expenseTimePeiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expensetimeperiod')),
            ],
        ),
    ]
