# Generated by Django 3.2.5 on 2021-07-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense_expensecategory_expensetimeperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetimeperiod',
            name='dateEnd',
            field=models.DateField(verbose_name='dateEnd'),
        ),
        migrations.AlterField(
            model_name='expensetimeperiod',
            name='dateStart',
            field=models.DateField(verbose_name='dateStart'),
        ),
    ]
