# Generated by Django 3.2.5 on 2021-08-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210727_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expenseTimePeiod',
            new_name='expenseTimePeriod',
        ),
    ]
