# Generated by Django 3.2.5 on 2021-08-17 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210801_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='groupTransactions',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='expensetimeperiod',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenseTimePeriod', to='core.expensecategory'),
        ),
    ]
